FROM node:20

# set working directory
WORKDIR /app

# copy package.json
COPY package*.json ./

# install dependencies
RUN npm install

# copy all source code
COPY . .

# expose port
EXPOSE 3000

CMD ["npm", "start"]